package concurrency.labs.sms.common.model;

import java.util.Date;

/**
 * NoteTask generated by MyEclipse Persistence Tools
 */

public class NoteTask implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Long id;

	private String creatorid;

	private String taskname;

	private Long smsendnum;

	private String operationtype;

	private String suboperationtype;

	private Long sendtype;

	private String orgaddr;

	private String destaddr;

	private String smContent;

	private Date sendtime;

	private Long needstatereport;

	private String serviceid;

	private String feetype;

	private String feecode;

	private String msgid;

	private Long smtype;

	private String messageid;

	private Long destaddrtype;

	private Date subtime;

	private Long taskstatus;

	private Long sendstate;

	private Long sendlevel;

	private Long trytimes;

	private Long count;

	private Long successid;

	private String reserve1;

	private String reserve2;

	private String submitresult;

	private String reportresult;

	private String reporterror;

	private String outmsgid;

	private Long appid;

	// Constructors

	/** default constructor */
	public NoteTask() {
	}

	/** minimal constructor */
	public NoteTask(Long id, String creatorid, Long smsendnum,
			String operationtype, String orgaddr, String destaddr,
			Date sendtime, Long smtype, String messageid, Long destaddrtype,
			Date subtime, Long taskstatus, Long sendstate, Long sendlevel) {
		this.id = id;
		this.creatorid = creatorid;
		this.smsendnum = smsendnum;
		this.operationtype = operationtype;
		this.orgaddr = orgaddr;
		this.destaddr = destaddr;
		this.sendtime = sendtime;
		this.smtype = smtype;
		this.messageid = messageid;
		this.destaddrtype = destaddrtype;
		this.subtime = subtime;
		this.taskstatus = taskstatus;
		this.sendstate = sendstate;
		this.sendlevel = sendlevel;
	}

	/** full constructor */
	public NoteTask(Long id, String creatorid, String taskname, Long smsendnum,
			String operationtype, String suboperationtype, Long sendtype,
			String orgaddr, String destaddr, String smContent, Date sendtime,
			Long needstatereport, String serviceid, String feetype,
			String feecode, String msgid, Long smtype, String messageid,
			Long destaddrtype, Date subtime, Long taskstatus, Long sendstate,
			Long sendlevel, Long trytimes, Long count, Long successid,
			String reserve1, String reserve2) {
		this.id = id;
		this.creatorid = creatorid;
		this.taskname = taskname;
		this.smsendnum = smsendnum;
		this.operationtype = operationtype;
		this.suboperationtype = suboperationtype;
		this.sendtype = sendtype;
		this.orgaddr = orgaddr;
		this.destaddr = destaddr;
		this.smContent = smContent;
		this.sendtime = sendtime;
		this.needstatereport = needstatereport;
		this.serviceid = serviceid;
		this.feetype = feetype;
		this.feecode = feecode;
		this.msgid = msgid;
		this.smtype = smtype;
		this.messageid = messageid;
		this.destaddrtype = destaddrtype;
		this.subtime = subtime;
		this.taskstatus = taskstatus;
		this.sendstate = sendstate;
		this.sendlevel = sendlevel;
		this.trytimes = trytimes;
		this.count = count;
		this.successid = successid;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCreatorid() {
		return this.creatorid;
	}

	public void setCreatorid(String creatorid) {
		this.creatorid = creatorid;
	}

	public String getTaskname() {
		return this.taskname;
	}

	public void setTaskname(String taskname) {
		this.taskname = taskname;
	}

	public Long getSmsendnum() {
		return this.smsendnum;
	}

	public void setSmsendnum(Long smsendnum) {
		this.smsendnum = smsendnum;
	}

	public String getOperationtype() {
		return this.operationtype;
	}

	public void setOperationtype(String operationtype) {
		this.operationtype = operationtype;
	}

	public String getSuboperationtype() {
		return this.suboperationtype;
	}

	public void setSuboperationtype(String suboperationtype) {
		this.suboperationtype = suboperationtype;
	}

	public Long getSendtype() {
		return this.sendtype;
	}

	public void setSendtype(Long sendtype) {
		this.sendtype = sendtype;
	}

	public String getOrgaddr() {
		return this.orgaddr;
	}

	public void setOrgaddr(String orgaddr) {
		this.orgaddr = orgaddr;
	}

	public String getDestaddr() {
		return this.destaddr;
	}

	public void setDestaddr(String destaddr) {
		this.destaddr = destaddr;
	}

	public String getSmContent() {
		return this.smContent;
	}

	public void setSmContent(String smContent) {
		this.smContent = smContent;
	}

	public Date getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}

	public Long getNeedstatereport() {
		return this.needstatereport;
	}

	public void setNeedstatereport(Long needstatereport) {
		this.needstatereport = needstatereport;
	}

	public String getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(String serviceid) {
		this.serviceid = serviceid;
	}

	public String getFeetype() {
		return this.feetype;
	}

	public void setFeetype(String feetype) {
		this.feetype = feetype;
	}

	public String getFeecode() {
		return this.feecode;
	}

	public void setFeecode(String feecode) {
		this.feecode = feecode;
	}

	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	public Long getSmtype() {
		return this.smtype;
	}

	public void setSmtype(Long smtype) {
		this.smtype = smtype;
	}

	public String getMessageid() {
		return this.messageid;
	}

	public void setMessageid(String messageid) {
		this.messageid = messageid;
	}

	public Long getDestaddrtype() {
		return this.destaddrtype;
	}

	public void setDestaddrtype(Long destaddrtype) {
		this.destaddrtype = destaddrtype;
	}

	public Date getSubtime() {
		return this.subtime;
	}

	public void setSubtime(Date subtime) {
		this.subtime = subtime;
	}

	public Long getTaskstatus() {
		return this.taskstatus;
	}

	public void setTaskstatus(Long taskstatus) {
		this.taskstatus = taskstatus;
	}

	public Long getSendstate() {
		return this.sendstate;
	}

	public void setSendstate(Long sendstate) {
		this.sendstate = sendstate;
	}

	public Long getSendlevel() {
		return this.sendlevel;
	}

	public void setSendlevel(Long sendlevel) {
		this.sendlevel = sendlevel;
	}

	public Long getTrytimes() {
		return this.trytimes;
	}

	public void setTrytimes(Long trytimes) {
		this.trytimes = trytimes;
	}

	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	public Long getSuccessid() {
		return this.successid;
	}

	public void setSuccessid(Long successid) {
		this.successid = successid;
	}

	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getSubmitresult() {
		return submitresult;
	}

	public void setSubmitresult(String submitresult) {
		this.submitresult = submitresult;
	}

	public String getReportresult() {
		return reportresult;
	}

	public void setReportresult(String reportresult) {
		this.reportresult = reportresult;
	}

	public String getReporterror() {
		return reporterror;
	}

	public void setReporterror(String reporterror) {
		this.reporterror = reporterror;
	}

	public String getOutmsgid() {
		return outmsgid;
	}

	public void setOutmsgid(String outmsgid) {
		this.outmsgid = outmsgid;
	}

	public Long getAppid() {
		return appid;
	}

	public void setAppid(Long appid) {
		this.appid = appid;
	}

}